### PR TITLE
LRQA-80188 | LRQA-80908

### PR DESCRIPTION
**Pull request by catarineaguiar**
Hi @zhangyan0701, I have decided sending only the fix for Bundle Blacklist testcases because the Clustering testcases will need more investigation. I opened this ticket for it https://liferay.atlassian.net/browse/LRQA-81189

Tested on https://github.com/catarineaguiar/liferay-portal/pull/97

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Hi Cata, just a question about the element ApplicationsMenu#TOGGLE. I was trying to figure out under what conditions it can be found by path `//button[@title='Applications Menu']`, I started U83 and run a BundleBlacklist test, but I could always find this element by `//button[@data-qa-id='applicationsMenu']` only. So I am curious how to make path `//button[@title='Applications Menu']` work? And why it can fix this issue?

**Comment by catarineaguiar** [comment]
@catarineaguiar Actually I forgot to remove this commit, it was for clustering issue, but I believe it is not related. Sorry for that

**Comment by catarineaguiar** [comment]
I have added a commit for https://liferay.atlassian.net/browse/LRQA-80908. Tested here https://github.com/catarineaguiar/liferay-portal/pull/99

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar 

The fixes look good to me! But there is a conflict in BundleBlacklist.testcase file, could you resolve it and resend? Thanks!

**Comment by catarineaguiar** [comment]
see https://github.com/zhangyan0701/liferay-portal/pull/527

**Pull request closed without merging**
