### PR TITLE
LRQA-81070

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://liferay.atlassian.net/browse/LRQA-81070

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
LGTM!
See https://github.com/vicnate5/liferay-portal/pull/2407.

**Pull request closed without merging**
