### PR TITLE
Test63981 1

### PR DESCRIPTION
**Pull request by zhangyan0701**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by vicnate5** [comment]
@zhangyan0701 I asked for help from LCS team to clear the current overload project, but can you go ahead and push this text fix through?

**Comment by zhangyan0701** [comment]
@vicnate5 Sent the fix to you: https://github.com/vicnate5/liferay-portal/pull/1621

**Pull request closed without merging**
