### PR TITLE
LRQA-78590 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LRQA-78590

Tested on https://github.com/catarineaguiar/liferay-portal/pull/54

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Review by zhangyan0701 — CHANGES_REQUESTED** [review]

**Comment by zhangyan0701** [comment]
@catarineaguiar Please see my comments and resend. Thanks!

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
Thanks! See https://github.com/vicnate5/liferay-portal/pull/2221.

**Pull request closed without merging**
