### PR TITLE
LRQA-75164

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
@zhangyan0701 
No testing is needed. This should not break any tests. Thanks!

**Comment by zhangyan0701** [comment]
Hi @koor4356 

Actually I don't really understand the ticket, I don't know much about integration tests and which team they should belong to. But after your changes, functional tests which component is Templates Engine will also move to Echo team, right? Is that also the purpose of the ticket?

Hi @kyle-miho, could you take a look on this? I am not sure if this is what the ticket wants. Thanks!

**Comment by vicnate5** [comment]
@kyle-miho as we discussed on Slack, please send me the correct fix for this issue.

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
