### PR TITLE
Master qa 59373 1

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-59373

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
I couldn't pin point the exact cause of the interruption yet. But it looks like the test opens two iframes, closes one, and tries to selectFrame the remaining one but fails to see an event fire.

**Comment by john-co** [comment]
I wonder if we can get away with using selectFrameNoLoading for that step since it's possible it doesn't need to load. However, I noticed a spa loading bar within the iframe while it updated the clay card with the selected web content. So we may need to add a WaitForSPARefresh(); right before?

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @john-co Thanks for reviewing this!

Using selectFrameNoLoading works for this test. Test can pass locally. Not sure if we need WaitForSPARefresh();, because spa loading bar within the iframe doesn't affect test running locally, so I rerun ci test to check the result on CI.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by john-co** [comment]
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1232023224&testrayRunIdA=1231982231&statusB=2

Looks like 4 tests are still affected: 
- ContentPagesWithContributedFragments#ShowTitleOfCollectionItemsInCollectionDisplay
- KnowledgebaseUsecase#DeleteConfiguredKBFolder
- SiteMemberships#OrganizationsView
- SPA#AssertLoadingBar

**Comment by john-co** [comment]
For the SPA test, since it's explicitly checking for SPA to run, maybe we can have a clickNoInitializeLiferayEventLog to avoid the reinitialize/waitForSPA.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
@john-co  Thanks for taking look at this! I made some changes and will check the results tomorrow.

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
seems like there was a jenkins slave issue.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Failures look unrelated, but will confirm locally tomorrow.

**Comment by zhangyan0701** [comment]
Passed on local:
LocalFile.WorkflowWiki#ApproveFrontPageUserEdit
LocalFile.DepotWC#EditWebContent
LocalFile.DepotRecycleBin#RestoreWebContent
LocalFile.ContentPagesWithContributedFragments#MapImageViaContentDisplay
LocalFile.ContentPages#EditContentPage

Know issues:
LocalFile.AppBuilder#SetAppBuilderManagePermissionFor2RolesAndPerformCRUD:
https://issues.liferay.com/browse/LRQA-59920
LocalFile.ApplicationDisplayTemplatesUseCase#ADTCategoriesNavigation:
https://issues.liferay.com/browse/LPS-116261
LocalFile.ContentPagesWithContributedFragments#MapImageViaContentDisplay
https://issues.liferay.com/browse/LRQA-60024

Looks like a flaky:
LocalFile.PortalSmoke#Smoke: This failed on Weblogic, page was loaded for a long time. Passed in the previous run.

**Pull request closed without merging**
