### PR TITLE
LRQA-75105

### PR DESCRIPTION
**Pull request by koor4356**
- LRQA-75105 Add condition to stabilize to the license test
- LRQA-75105 Move Sign in to the test level

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:license

**Comment by zhangyan0701** [comment]
ci:test:license

**Comment by zhangyan0701** [comment]
ci:forward

**Comment by zhangyan0701** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/119122. Thanks!

**Pull request closed without merging**
