### PR TITLE
LPS 170709 12 13 test

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:service-builder

**Comment by kyle-miho** [comment]
ci:test:backend

**Comment by kyle-miho** [comment]
@zhangyan0701 This marker might fix the complaint about the lfr-ci marker file, if not we will have to find a better fix

**Comment by zhangyan0701** [comment]
Thanks @kyle-miho for helping with this! Could you take a look more why the service builder integration tests are stilling running on modules-integration-* test batches? Like this example https://testray.liferay.com/home/-/testray/case_results/2126446142, and failed with BundleException. But I excluded the service builder here https://github.com/zhangyan0701/liferay-portal/pull/428/commits/c0331f6d75d2dc073d55259511e3e310a38acfc0#diff-0dc5a96f7041113b3e2e0777ee0f3118e2b6bb53b4bd82a73ebd5228e8ee4da7R1036. Did I do wrongly or there are something I  missed?

**Comment by vicnate5** [comment]
I am picking this up

**Comment by vicnate5** [comment]
@zhangyan0701 I used [this feature to debug the issue](https://liferay.atlassian.net/wiki/spaces/QA/pages/2150729536/What+Test+Suite+Should+I+Use+for+CI#Granular-Level%3A-Using-Job-Summary) here with service-builder and backend suites (I needed the LA office VPN to use) 

See https://github.com/liferay-core-infra/liferay-portal/pull/2751

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
