### PR TITLE
LPS 205346 LPS 206089 1

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-206089 Enable the defaultVirtualHost for each item of VirtualHost make SampleSQLBuilder generated data more consistent with default portal
- LPS-205346 Add unit test to do benchmark test for logic locally
- LPS-205346 Add logging to help developer use the generated data correctly
- LPS-205346 Export package, prepare for adding integration test
- LPS-205346 Add integration test
- LPS-205346 Add marker files to deploy on CI

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @dantewang 

The module portal-tools-benchmark was deployed. But benchmark tests failed.

1. Unit test [LoginBenchmarkTest](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883775/testReport/com.liferay.portal.tools.benchmark/LoginBenchmarkTest/testLogin/) failed with error `Communications link failure`. Full console log: https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/883775/consoleFull.
I think this maybe because `modules-unit-jdk8` doesn't start a database instance and portal. Does this test require a database instance?

3. Integration test [LoginBenchmarkTaskTest](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764037/testReport/com.liferay.portal.tools.benchmark.test/LoginBenchmarkTaskTest/testExecute/) failed with error `Response status code is wrong! Expect 200 but actual is 301` even with [your new commit](https://github.com/zhangyan0701/liferay-portal/pull/593/commits/9da64c794b521ec3562e64cdf2ecc23a72003d5f).
Full console log: https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764037/consoleFull

**Comment by dantewang** [comment]
@zhangyan0701 Yes the unit test is designed to be so, and we can ignore it.

For the integration test, I wonder whether there's a host name that we usually use on CI? That must be different than localhost, and accessible on any CI node.

**Comment by zhangyan0701** [comment]
@dantewang

Not sure if this is the host name that can be used in the test, but in Jenkins console, you can find a HOSTNAME property, such as in this log https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764037/consoleFull: `HOSTNAME=test-1-39-40.lax.liferay.com`. This is the hostname of the Jenkins server that the test is running on.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@dantewang 

Test failed with the same error: 
```
[beanshell]      [exec] com.liferay.portal.tools.benchmark.test.LoginBenchmarkTaskTest > testExecute FAILED
[beanshell]      [exec]     java.lang.IllegalStateException: Response status code is wrong! Expect 200 but actual is 301
```
https://testray.liferay.com/reports/production/logs/2024-01/test-1-33/test-portal-acceptance-pullrequest(master)/4966/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Test [com.liferay.portal.tools.benchmark.test.LoginBenchmarkTaskTest](https://testray.liferay.com/home/-/testray/case_results/2492490651) passed here.

**Pull request closed without merging**
