### PR TITLE
Lrqa 73874

### PR DESCRIPTION
**Pull request by zhangyan0701**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
It passed: [Testray result](https://testray.liferay.com/home/-/testray/case_results/1916282004?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1916281727%26testrayRunId%3D1916281937%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:stop

**Pull request closed without merging**
