### PR TITLE
LPS-135570 Portal class loader now is different with App Server's class loader due to shielded container

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @dantewang 

I could reproduced https://issues.liferay.com/browse/LPS-135570 with the changes in the PR.

In the cluster.*.log file of the second node, below error thrown:
```
30-Jul-2021 11:29:11.716 严重 [Tribes-Task-Receiver[Catalina-Channel]-3] org.apache.catalina.ha.session.DeltaManager.deserializeSessions 加载持久化会话 [java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.TransientValue] 时出现ClassNotFoundException
	java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.TransientValue
```

**Pull request closed without merging**
