### PR TITLE
56272test

### PR DESCRIPTION
**Pull request by zhangyan0701**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by vicnate5** [comment]
@zhangyan0701 There could be a problem with the xml file replace. Are you able to run these tests locally the ant scripts?
1. `ant compile`
2. `ant -f build-dist.xml build-dist-wildfly`
3. `ant -f build-test-wildfly.xml run-selenium-wildfly -Dtest.class=`

It would help to know that this is working locally.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
Hi @vicnate5 

Yes, there is a problem with the wildfly standalone.xml file. I failed to run the test locally, server couldn't start up neither. I updated the xml file, and rerun the tests on CI to see if works. Also run the regular smoke to see it also have the stop app server error.

Thanks so much for help!!

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
Re-running this longer mysql timeout

**Comment by vicnate5** [comment]
@zhangyan0701 Double the timeout did not fix the issue. Did you confirm that this issue is not reproducible by just shutting down Websphere locally? This is only on CI or if you manually kill the database?

If this is true, I think we can treat this as a separate problem for now and move forward merging these tests. Please make a new LRQA ticket so we can address this in the future.

But if you can reproduce any of this locally (without manually killing the database), then please create an LPS ticket so we can address this as a bug.

Either way, resend this with correct commit descriptions so we can merge the tests.

**Comment by zhangyan0701** [comment]
Thanks for reviewing! 
I couldn't reproduce on local by just shutting down Websphere. I only saw this error if I manually kill the database before portal completely stopping.

I will create a new ticket and resend you the test.

Regards!

**Comment by zhangyan0701** [comment]
ci:test:sf

**Pull request closed without merging**
