### PR TITLE
master-qa-58712

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-58712

This is only for master, thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Great job being able to reproduce it @zhangyan0701! When I try it out and disable the css `display: flex` on our master test server it doesn't seem to cause extreme chaos, just some alignment issues. And it's only one css property, was that the only css property that changed? I wonder if there's something to cast a bigger safety net if other elements/properties changed between refresh.

Like...does any of the html structure change between refresh? or was it only the css that changed? I wonder if we could do something similar as https://stackoverflow.com/questions/3242640/need-to-compare-2-html-documents-using-java-selenium and use `selenium.getHtmlSource()` before and after refresh and compare the two.

I think the css `display: flex` assertion is ok as a temporary fix so we can get the test back online, but I think it would be worth exploring the html/css diff comparison in the future.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @john-co 

I added one more step in tests that assert the list-style property in CSS.
The Control Menu has it's own CSS class ".control-menu-nav" which define the display as "flex" and list-style as "none". When reproduce that bug, the Control Menu doesn't have class ".control-menu-nav", so it inherits style from body which display style is "block" and list-style is "disc".

I manually changed this two properties, and the control menu was broken. 


I also compared the html source, but didn't see useful difference. So assert the two propertied as temporary fix. Asserting these two properties can catch this bug, but if we need to assert more, we can add in the future. Is this OK?

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:forward

**Comment by john-co** [comment]
@zhangyan0701 looks good! Thanks!

**Comment by john-co** [comment]
The `property portal.upstream = "quarantine";` is still set. Can you remove this and check it passes CI? Also, let's backport this to 7.2.x as well.

**Pull request closed without merging**
