### PR TITLE
LRQA-73140

### PR DESCRIPTION
**Pull request by catarineaguiar**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@zhangyan0701 I tried to do what you suggest, can you test it on the release bundle? Thanks

**Comment by zhangyan0701** [comment]
I triggered a release job here https://test-1-1.liferay.com/job/test-portal-release/3573/, hoping this time the fix can work.

**Comment by catarineaguiar** [comment]
It didn't work :(

**Comment by catarineaguiar** [comment]
I started this analysis to test other solution https://test-1-1.liferay.com/job/test-portal-release/3575/

**Comment by catarineaguiar** [comment]
Running on https://test-1-1.liferay.com/job/test-portal-release/3585/

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Pushed to Victor:
https://github.com/vicnate5/liferay-portal/pull/2183

Thanks!

**Pull request closed without merging**
