### PR TITLE
Master qa 62432 sf

### PR DESCRIPTION
**Pull request by zhangyan0701**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@wincent Can you help look at it?
I don't understand the failures, and why Prettier did auto fix file?

Thanks.

**Comment by wincent** [comment]
> I don't understand the failures, and why Prettier did auto fix file?

So if you `cd modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web` and run `yarn run format` it will produce this diff (you can also run the Gradle `formatSource` task from that directory, but I usually use `yarn` directly because it has less overhead — 3.43 seconds for Yarn vs 47.11 seconds for Gradle):

```diff
diff --git a/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js b/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js
index 16e6a12035ab..89f9c39617cd 100644
--- a/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js
+++ b/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js
@@ -28,30 +28,25 @@ export default () => {
 			title: Liferay.Language.get('success'),
 			type: 'success',
 		});
-	}
+	};
 
 	const onClickFail = () => {
 		openToast({
-			message: Liferay.Language.get(
-				'an-unexpected-error-occurred'
-			),
+			message: Liferay.Language.get('an-unexpected-error-occurred'),
 			title: Liferay.Language.get('error'),
 			type: 'danger',
 		});
-	}
+	};
 
 	return (
 		<div>
 			<ClayAlert title="Info">
-				This widget is used to test out Clay Toast Alert. 
+				This widget is used to test out Clay Toast Alert.
 			</ClayAlert>
-		
+
 			<div className="sheet-footer">
 				<ClayButton.Group spaced>
-					<ClayButton
-						onClick={onClickSuccess}
-						type="submit"
-					>
+					<ClayButton onClick={onClickSuccess} type="submit">
 						{Liferay.Language.get('success-submit')}
 					</ClayButton>
```

So, wrapping changes on some lines and removing trailing whitespace on another.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Hi @ling-alan-huang @wincent Thanks a lot for the helping!

**Comment by ling-alan-huang** [comment]
Thanks @wincent, actually I ran `ant format-source-files` before asking you, it didn't changes anything, that's the reason why I was asking...

**Comment by wincent** [comment]
Yeah, @ling-alan-huang, I very rarely run `ant format-anything` if I can help it because it is even slower than Gradle... But `ant format-source-current-branch` from `portal-impl/` with this PR checked out does indeed fix the formatting of that file for me; just takes three-and-a-half minutes to do it (output edited for brevity follows):

```
❯ cd portal-impl
❯ ant format-source-current-branch
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
Buildfile: /Users/greghurrell/code/portal/liferay-portal/portal-impl/build.xml
   [delete] Deleting: /Users/greghurrell/code/portal/liferay-portal/null231766636.properties

format-source-current-branch:
   [delete] Deleting: /Users/greghurrell/code/portal/liferay-portal/null231766636.properties

format-source-files:
     [java] Loading file:/Users/greghurrell/code/portal/liferay-portal/portal-impl/classes/system.properties
     ...
     [exec]
     [exec] > Task :packageRunFormat
     [exec] yarn run v1.13.0
     [exec] $ liferay-npm-scripts fix
     [exec]
     [exec] Prettier checked 5 files, fixed 1 file
     [exec] Done in 48.60s.
     [exec]
     [exec] > Task :portalYarnFormat
     [exec]
     [exec]
     [exec] BUILD SUCCESSFUL in 1m 43s
     [exec] 2 actionable tasks: 2 executed

BUILD SUCCESSFUL
Total time: 3 minutes 29 seconds
❯ git diff | head
diff --git a/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js b/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js
index 16e6a12035ab..89f9c39617cd 100644
--- a/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js
+++ b/modules/apps/frontend-js/frontend-js-test/frontend-js-test-clay-toast-alert-sample-web/src/main/resources/META-INF/resources/js/App.js
@@ -28,30 +28,25 @@ export default () => {
 			title: Liferay.Language.get('success'),
 			type: 'success',
 		});
-	}
+	};
```

**Comment by ling-alan-huang** [comment]
Oh, it works?! Interesting...I will looking into why `ant format-source-files `doesn't change it..Thanks again @wincent

**Pull request closed without merging**
