### PR TITLE
LPS-144124 Fix regex to catch more cases to check Poshi dependencies archive expansion

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Here are the steps that you can use unpublished SF to check 7.*.x(If want to try when you fixed them on 7.*.x.)

1. Create a branch from `master`, and cherry-pick my changes. Or you can just use this branch.
2. Go to `liferay-portal/modules/util/source-formatter`, run `../../../gradlew deploy`
3. Go to `portal-impl`, run `ant format-source-all -Dsource.base.dir=/Users/alan/liferay_code/7.0.x/7.3.x-liferay-portal-ee`

For example use SF to check 7.3.x:
```
alan@iMac:~/liferay_code/master/liferay-portal/portal-impl[LPS-144124_PoshiSourceProcessor_20220310]$ ant format-source-all -Dsource.base.dir=/Users/alan/liferay_code/7.0.x/7.3.x-liferay-portal-ee
Buildfile: /Users/alan/liferay_code/master/liferay-portal/portal-impl/build.xml
   [delete] Deleting: /Users/alan/liferay_code/master/liferay-portal/null1669085458.properties

format-source-all:
   [delete] Deleting: /Users/alan/liferay_code/master/liferay-portal/null1669085458.properties

format-source-files:
     [java] Loading file:/Users/alan/liferay_code/master/liferay-portal/portal-impl/classes/system.properties
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/Users/alan/liferay_code/master/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/Users/alan/liferay_code/master/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Do not add archive files for tests, they must be expanded: /Users/alan/liferay_code/7.0.x/7.3.x-liferay-portal-ee/modules/apps/wiki/wiki-test/src/testIntegration/resources/com/liferay/wiki/service/test/dependencies/media_link_test.zip
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)

BUILD FAILED
/Users/alan/liferay_code/master/liferay-portal/portal-impl/build.xml:440: The following error occurred while executing this line:
/Users/alan/liferay_code/master/liferay-portal/portal-impl/build.xml:593: Java returned: 1

Total time: 10 minutes 23 seconds
alan@iMac:~/liferay_code/master/liferay-portal/portal-impl[LPS-144124_PoshiSourceProcessor_20220310]$ 


```

**Comment by zhangyan0701** [comment]
Hi @ling-alan-huang 

Below two files are for integration tests, they are not using in Poshi functional tests, so I don't think we should check them.
```
[java] 2: Do not add archive files for tests, they must be expanded: ./modules/apps/portal/portal-tika-test/src/testIntegration/resources/com/liferay/portal/tika/test/dependencies/test.lar
[java] 4: Do not add archive files for tests, they must be expanded: ./modules/apps/wiki/wiki-test/src/testIntegration/resources/com/liferay/wiki/service/test/dependencies/media_link_test.zip
```
/cc @vicnate5 Could you confirm?

**Comment by vicnate5** [comment]
@ling-alan-huang The integration tests dependencies are out of immediate scope, however, I expect Brian would want those expanded too. I just expect that would require a fix for the integration test code/framework, which QA would not be the best team to handle.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Pull request closed without merging**
