### PR TITLE
LRQA-82622 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://liferay.atlassian.net/browse/LRQA-82622

Tested on: https://github.com/catarineaguiar/liferay-portal/pull/124

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@catarineaguiar I saw this article before and could see that aws use GTM time zone, so I believe using this same time zone on our aws tests is the simpler way to solve this problem.

**Comment by catarineaguiar** [comment]
we can run the test suite several times to check if it really works

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
See https://github.com/vicnate5/liferay-portal/pull/2429.

**Pull request closed without merging**
