### PR TITLE
LRQA-72515 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LRQA-72515

Tested [here](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1946342639)

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar 

I took a look on the test results:
https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1946342639

There are two errors that happen consistently:
1. https://testray.liferay.com/home/-/testray/case_results/1946343945
`com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//button[contains(.,'Done')]"`

Seems like we don't need this step anymore as we added the property "enterprise.product.notification.enabled=false" to disable the pop up. Could you try removing the step and test it?

2. Console text assertion fail on some database types, such as:
https://testray.liferay.com/home/-/testray/case_results/1946343842
`java.lang.Exception: "Using dialect com.liferay.portal.dao.orm.hibernate.DB2Dialect for DB2" is not present in console`

It says "Unable to find the JDBC driver class com.ibm.db2.jcc.DB2Driver in a JAR in the directory /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/shielded-container-lib/" in portal log.

This affects DB2, MariaDB, Sybase, Oracle, SQLServer and PostgreSQL. Could you investigate more why the drivers are missing?

Thanks!

**Comment by catarineaguiar** [comment]
Closing to investigate.

**Pull request closed without merging**
